### ISSUE TITLE
relicense gosdc as MPLv2

### ISSUE THREAD

**Issue by bcantrill** [joyent/gosdc#11]
gosdc was mistakenly licensed as LGPL:  LGPL is not a license that we at Joyent use for de novo software, and (bluntly) no one noticed that this wasn't licensed as MIT (our preference for node modules) or MPLv2 (our preference for entirely new work).  While having a few external contributors, Joyent has retained copyright, and we are therefore making the decision to relicense gosdc as MPLv2 as per our own policy.  We are believers in the MPLv2 because we believe that it captures the spirit of the LGPL but with much less ambiguity (and therefore in a way that is much more palatable for integration into larger works) -- so hopefully those external contributors (specifically, @wallyworld and @BrianHicks) who contributed to gosdc as an LGPL project won't feel wronged by the fact that it's now an MPLv2 one!

**Comment by elijah** [comment]
+1, dude.  :)

**Comment by jen20** [comment]
Awesome - thanks!

**Comment by BrianHicks** [comment]
Thanks for the clarification on this. Personally, I'm cool with it. But technically, my contributions were under contract with Joyent, so they're yours to do with what you wish! 😎
