### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by rafecolton** [joyent/gosdc#2]
It would be extremely useful to have an example of how to use this library, targeted at somebody who is used to using the `sdc-*` tools

**Comment by BrianHicks** [comment]
@rafecolton how does #13 look for your case?

**Comment by rafecolton** [comment]
I no longer work at a company that uses Joyent, so I don't have a use case any more.  That being said, it looks like a decent start.

Does this library handle the case where my ssh key is password protected?  The `sdc-` tools would look at the keys in my ssh agent and use the correct one.  I would only have to enter the password once - when I add the key to my agent.  I remember not being able to use gosdc at all with a password-protected key.  If memory serves, this functionality is what I meant by "somebody who is used to using the `sdc-*` tools".

**Comment by BrianHicks** [comment]
AFAICT it doesn't support that right now (I got bit by it too.) I've opened #14 to document that use, because it's totally valid.

**Comment by rafecolton** [comment]
Awesome, thank you for #14
