### ISSUE TITLE
CreateMachine with tags/metadata doesn't work as expected

### ISSUE THREAD

**Issue by MerlinDMC** [joyent/gosdc#3]
The `map[string]string` for both gets ignored by the SDC endpoint.
Creation of the machine is successful but tags and metadata are missing.

The JS client does need those settings in form of a flatmap as well to be processed by SDC for example:
```javascript
opts = {
  tags: {
    "foo": "bar"
  }
}
```

would be provided as:
```javascript
opts = {
  "tags.foo": "bar"
}
```

I can't see the flattening happen in the go implementation so I assume this might be the cause.

`AddMachineTags` and `UpdateMachineMetadata` work with the normal `map[string]string` structure just fine.

Stupid dummy to reproduce:
```go
package main

import (
	"log"

	"github.com/joyent/gocommon/client"
	"github.com/joyent/gocommon/jpc"
	"github.com/joyent/gosdc/cloudapi"
)

func main() {
	opts := cloudapi.CreateMachineOpts{
		Image:   "bae9b95e-10c0-11e4-89d4-9fb9155d8bda",
		Package: "g3-devtier-0.25-smartos",
		Metadata: map[string]string{
			"meta_key": "meta_value",
		},
		Tags: map[string]string{
			"foo": "bar",
		},
	}

	if creds, err := jpc.CompleteCredentialsFromEnv(""); err == nil {
		sdc_client := cloudapi.New(client.NewClient(creds.SdcEndpoint.URL, cloudapi.DefaultAPIVersion, creds, &cloudapi.Logger))

		_, err := sdc_client.CreateMachine(opts)
		if err != nil {
			log.Panicf("Error creating instance: %s", err)
		}
	}
}
```

Neither the portal nor the `sdc-getmachine` cli does see tags or metadata created for this.

**Comment by BrianHicks** [comment]
I'm seeing this too. I think it's because those fields in `CreateMachineOpts` are never serialized to JSON: https://github.com/joyent/gosdc/blob/master/cloudapi/cloudapi.go#L483-L484. Should be a pretty simple fix if that's what it is.

**Comment by MerlinDMC** [comment]
@BrianHicks my problem probably was that cloudapi wants to get those tags prefixed with `tag.`.
I changed my code to prefix all entries and it did work just fine after that.

https://github.com/MerlinDMC/terraform/blob/feature/add_sdc_provider/builtin/providers/sdc/resource_compute_instance.go#L288-L306

But I think if that is what is intended to be used in the back the map given to cloudapi should be without the prefix - that at least is what I was expecting in the first place.
