### ISSUE TITLE
Machine doesn't include FirewallEnabled

### ISSUE THREAD

**Issue by BrianHicks** [joyent/gosdc#9]

**Comment by BrianHicks** [comment]
Update: the API doesn't return if the firewall is enabled or not on machines. Closing.

https://apidocs.joyent.com/cloudapi/#GetMachine

**Comment by misterbisson** [comment]
@xer0x would we consider this a bug in CloudAPI?

**Comment by xer0x** [comment]
Yes,we should fix this. I'll create a ticket for it.
